### ISSUE TITLE
[EPIC] UI Updates

### ISSUE THREAD

**Issue by Gkrumbach07** [Gkrumbach07/thoth-search#72]
**Is your feature request related to a problem? Please describe.**
After a conversation with a UI/UX expert, I have formulated a list of fixes to the UI of Thoth Search.

**Acceptance Criteria**
- [x] #75
- [x] align spacing on edges of cards
- [x] convert large header into small header
     - ~~Use breadcrumb navigation  `Home / adviser-213123132... / summary`~~
     - [x] move adviser doc name and completion to just the summary page or on the header
     - [x] move logs to its own tab
- [x] have latest log shown when advise is loading ( ~~possibly a web-socket with the log endpoint?~~ )
- [x] prioritize info on the summary page at the top (priority on most critical info about the environment)
- [x] #91
     - [x] adding more internal linking between components and justifications
     - ~~add more complex table on detail page so user can be linked to filters on licensees and other metadata~~
     - ~~add more columns to the details package table~~
     - [x] be able to link to specific sections and searches on the details and compare pages
- [x] break up the licenses summary metric card accordion into root, direct, indirect (labeled)
- [x] possibly incorporate (fig-1) into Thoth justifications on detail page
- [x] possibly look into using different graphs and visualizations that compare data better compared to (fig-2). Or remove them if they don't provide value.

**fig-1**
![image](https://user-images.githubusercontent.com/12587674/162518721-97c21a3d-56c6-49b9-b338-ec65a2bb7713.png)

**fig-2**
<img width="327" alt="image" src="https://user-images.githubusercontent.com/12587674/162518891-1f631861-0c6e-4151-88d2-215d695faa5c.png">

**Comment by Gkrumbach07** [comment]
Summary Page is up to date. Closing this issue as acceptance criteria that still is relevant has been met.

/close
